### PR TITLE
Added navbar hover effect as per #7

### PR DESCRIPTION
**Pull request by Palaksharma23**
I have added a hover effect on navbar items and it look great as per issue #7

### CODE REVIEW

**Review by JazParkyn — CHANGES_REQUESTED** [review]
Please remove the scale and the boxshadow - IMHO these look a little out of place:

image

Also the focus state is missing. Maybe also add styles to the active class too.

**Comment by Palaksharma23** [comment]
Sure @JazParkyn I will do it

**Comment by Palaksharma23** [comment]
i have commit changes please once review them @JazParkyn

**Comment by Palaksharma23** [comment]
@conconnl and @JazParkyn  can you please once review the changes that i have commited in thus pull request .

**Comment by brianteeman** [comment]
Please follow the code style of the rest of the file

**Comment by Palaksharma23** [comment]
@brianteeman  @JazParkyn @conconnl Can you please once review my last commit 
I have followed the code style of the rest of the file and here i am attaching the screenshots as well

Initial State 

initial

Hover State

hover

Active State

active

Regards

**Pull request closed without merging**
